# vim: set ft=yaml ts=2 sw=2 expandtab:
name: Test Suite
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: "Build"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    defaults:
      run:
        shell: bash
    runs-on: "${{ matrix.os }}"
    timeout-minutes: 5
    steps: 
      - name: Check out code
        uses: actions/checkout@v4
      - name: Touch all code  # workaround odd autoconf problems
        run: touch *
      - name: Run configure step
        run: ./configure
      - name: Build the source distribution
        run: make dist-gzip
      - name: Build the code
        run: make
      - name: Print a banner
        run: ./banner Success!
      - name: Clean up
        run: make distclean
